services:
  db:
    image: postgres:15-alpine
    container_name: moqadb
    environment:
      POSTGRES_DB: moqadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: moqa-api
    volumes:
      - ./backend:/app
      - .:/data:ro


    ports:
      - "8000:8000"

    environment:
      - DB_NAME=moqadb
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=${DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-}

    depends_on:
      - db

  web:
    build: ./frontend
    container_name: moqa-web
    volumes:
      - ./frontend:/app
      - moqa_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    container_name: moqadb-backup
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=moqadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - SCHEDULE=@weekly
      - BACKUP_KEEP_DAYS=30
    volumes:
      - ./backups:/backups
    depends_on:
      - db


volumes:
  postgres_data:
  moqa_node_modules: