# Generated by Django 6.0.3 on 2026-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/', verbose_name='Foto'),
        ),
    ]
