# Generated by Django 6.0.3 on 2026-03-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_maintenance_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='cost',
        ),
    ]
