# Generated by Django 6.0.3 on 2026-03-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_maintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='moqa_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device'),
        ),
    ]
