# Generated by Django 6.0.3 on 2026-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_moqa_id_device_point_eventlog_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
