# Generated by Django 6.0.3 on 2026-03-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_legacy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.CharField(max_length=100, verbose_name='Técnico Responsável')),
                ('description', models.TextField(verbose_name='Descrição da Evolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='devices.maintenance', verbose_name='Ordem de Serviço')),
            ],
            options={
                'db_table': 'manutencao_evolucao',
                'ordering': ['-created_at'],
            },
        ),
    ]
