# Generated by Django 6.0.3 on 2026-04-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_maintenanceupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='photo',
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='maintenance_photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='devices.maintenance', verbose_name='Ordem de Serviço')),
            ],
            options={
                'db_table': 'manutencao_fotos',
                'ordering': ['created_at'],
            },
        ),
    ]
