spring.application.name=moqa-back
# Por enquanto, vamos desativar a conexão real para você conseguir compilar
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration